/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Key Station Documentation
 * API станции для выдачи ключей по пропуску преподавателей
 * OpenAPI spec version: 1.0
 */
import type { BaseResponse } from './baseResponse';
import type { CustomerControllerCreate200AllOf } from './customerControllerCreate200AllOf';

export type CustomerControllerCreate200 = BaseResponse & CustomerControllerCreate200AllOf;
