/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Key Station Documentation
 * API станции для выдачи ключей по пропуску преподавателей
 * OpenAPI spec version: 1.0
 */
import type { FindAllLogResponseDtoAction } from './findAllLogResponseDtoAction';
import type { CreatedCustomerDto } from './createdCustomerDto';
import type { Cell } from './cell';

export interface FindAllLogResponseDto {
  id: string;
  action: FindAllLogResponseDtoAction;
  cellId: string;
  customerId: string;
  timestamp: string;
  customer: CreatedCustomerDto;
  cell: Cell;
}
