/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Key Station Documentation
 * API станции для выдачи ключей по пропуску преподавателей
 * OpenAPI spec version: 1.0
 */
import type { CreatedCell } from './createdCell';

export interface FindAllCellsResponseDto {
  cells: CreatedCell[];
}
