/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Key Station Documentation
 * API станции для выдачи ключей по пропуску преподавателей
 * OpenAPI spec version: 1.0
 */
import type {
  AppControllerGetHealth200,
  AuthControllerCallbackParams,
  CellControllerFindAllParams,
  ConnectToProviderResponseDto,
  CreateCellDto,
  CreateCellResponseDto,
  CreateCustomerDto,
  FindAllCellsResponseDto,
  FindAllCustomersDto,
  FindAllLogsResponseDto,
  FindByRfidCustomerResponseDto,
  KeyLogControllerFindAllParams,
  LoginDto,
  LoginResponseDto,
  RegisterDto,
  ReturnKeyDto,
  TakeKeyDto,
  UpdateCustomerDto,
  UpdateUserDto
} from '../../model'
import { customInstance } from './axios';
import type { BodyType } from './axios';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


  /**
 * @summary Регистрация пользователя
 */
export const authControllerRegister = (
    registerDto: BodyType<RegisterDto>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/api/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerDto
    },
      options);
    }
  
/**
 * @summary Авторизация пользователя
 */
export const authControllerLogin = (
    loginDto: BodyType<LoginDto>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<LoginResponseDto>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginDto
    },
      options);
    }
  
/**
 * Используется провайдерами

Перенаправляет на фронт по адресу вместе с токеном /auth/callback?accessToken=ТОКЕН
 * @summary Авторизация через Oauth
 */
export const authControllerCallback = (
    provider: 'yandex' | 'github',
    params: AuthControllerCallbackParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/api/auth/oauth/callback/${provider}`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * @summary Получение ссылки на Oauth авторизацию
 */
export const authControllerConnect = (
    provider: 'yandex' | 'github',
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<ConnectToProviderResponseDto>(
      {url: `/api/auth/oauth/connect/${provider}`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Получение профиля пользователя
 */
export const userControllerFindProfile = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<unknown>(
      {url: `/api/user/profile`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Обновление профиля пользователя
 */
export const userControllerUpdateProfile = (
    updateUserDto: BodyType<UpdateUserDto>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<unknown>(
      {url: `/api/user/profile`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateUserDto
    },
      options);
    }
  
/**
 * @summary Получение пользователя по ID
 */
export const userControllerFindById = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<unknown>(
      {url: `/api/user/by-id/${id}`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Создание нового клиента системы (Преподаватели и ученики)
 */
export const customerControllerCreate = (
    createCustomerDto: BodyType<CreateCustomerDto>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<CreateCellResponseDto>(
      {url: `/api/customer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCustomerDto
    },
      options);
    }
  
/**
 * @summary Получение списка клиентов
 */
export const customerControllerFindAll = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<FindAllCustomersDto>(
      {url: `/api/customer`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Обновление клиента системы
 */
export const customerControllerUpdate = (
    updateCustomerDto: BodyType<UpdateCustomerDto>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<unknown>(
      {url: `/api/customer`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateCustomerDto
    },
      options);
    }
  
/**
 * @summary Получение клиента по пропуску
 */
export const customerControllerFindByRfid = (
    rfid: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<FindByRfidCustomerResponseDto>(
      {url: `/api/customer/${rfid}`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Удаление клиента системы
 */
export const customerControllerRemove = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<unknown>(
      {url: `/api/customer/${id}`, method: 'DELETE'
    },
      options);
    }
  
/**
 * @summary Создание ячейки сейфа
 */
export const cellControllerCreate = (
    createCellDto: BodyType<CreateCellDto>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<CreateCellResponseDto>(
      {url: `/api/cell`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCellDto
    },
      options);
    }
  
/**
 * @summary Получение списка ячеек
 */
export const cellControllerFindAll = (
    params?: CellControllerFindAllParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<FindAllCellsResponseDto>(
      {url: `/api/cell`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * @summary Заблокировать ячейку сейфа
 */
export const cellControllerBlock = (
    cellId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<unknown>(
      {url: `/api/cell/block/${cellId}`, method: 'POST'
    },
      options);
    }
  
/**
 * @summary Разблокировать ячейку сейфа
 */
export const cellControllerUnblock = (
    cellId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<unknown>(
      {url: `/api/cell/unblock/${cellId}`, method: 'POST'
    },
      options);
    }
  
/**
 * @summary Получение информации о ячейке
 */
export const cellControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<unknown>(
      {url: `/api/cell/${id}`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Удаление ячейки сейфа
 */
export const cellControllerRemove = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<unknown>(
      {url: `/api/cell/${id}`, method: 'DELETE'
    },
      options);
    }
  
/**
 * @summary Может ли пользователь выйти?
 */
export const cellControllerCanCustomerOut = (
    customerRfid: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<unknown>(
      {url: `/api/cell/canCustomerOut/${customerRfid}`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Взять ключ
 */
export const keyLogControllerTakeKey = (
    takeKeyDto: BodyType<TakeKeyDto>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<unknown>(
      {url: `/api/key/take`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: takeKeyDto
    },
      options);
    }
  
/**
 * @summary Вернуть ключ
 */
export const keyLogControllerReturnKey = (
    returnKeyDto: BodyType<ReturnKeyDto>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<unknown>(
      {url: `/api/key/return`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: returnKeyDto
    },
      options);
    }
  
/**
 * @summary Получение списка логов
 */
export const keyLogControllerFindAll = (
    params?: KeyLogControllerFindAllParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<FindAllLogsResponseDto>(
      {url: `/api/key/logs`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * @summary Проверка работоспособности БД
 */
export const appControllerGetHealth = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<AppControllerGetHealth200>(
      {url: `/api/health`, method: 'GET'
    },
      options);
    }
  
export type AuthControllerRegisterResult = NonNullable<Awaited<ReturnType<typeof authControllerRegister>>>
export type AuthControllerLoginResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>
export type AuthControllerCallbackResult = NonNullable<Awaited<ReturnType<typeof authControllerCallback>>>
export type AuthControllerConnectResult = NonNullable<Awaited<ReturnType<typeof authControllerConnect>>>
export type UserControllerFindProfileResult = NonNullable<Awaited<ReturnType<typeof userControllerFindProfile>>>
export type UserControllerUpdateProfileResult = NonNullable<Awaited<ReturnType<typeof userControllerUpdateProfile>>>
export type UserControllerFindByIdResult = NonNullable<Awaited<ReturnType<typeof userControllerFindById>>>
export type CustomerControllerCreateResult = NonNullable<Awaited<ReturnType<typeof customerControllerCreate>>>
export type CustomerControllerFindAllResult = NonNullable<Awaited<ReturnType<typeof customerControllerFindAll>>>
export type CustomerControllerUpdateResult = NonNullable<Awaited<ReturnType<typeof customerControllerUpdate>>>
export type CustomerControllerFindByRfidResult = NonNullable<Awaited<ReturnType<typeof customerControllerFindByRfid>>>
export type CustomerControllerRemoveResult = NonNullable<Awaited<ReturnType<typeof customerControllerRemove>>>
export type CellControllerCreateResult = NonNullable<Awaited<ReturnType<typeof cellControllerCreate>>>
export type CellControllerFindAllResult = NonNullable<Awaited<ReturnType<typeof cellControllerFindAll>>>
export type CellControllerBlockResult = NonNullable<Awaited<ReturnType<typeof cellControllerBlock>>>
export type CellControllerUnblockResult = NonNullable<Awaited<ReturnType<typeof cellControllerUnblock>>>
export type CellControllerFindOneResult = NonNullable<Awaited<ReturnType<typeof cellControllerFindOne>>>
export type CellControllerRemoveResult = NonNullable<Awaited<ReturnType<typeof cellControllerRemove>>>
export type CellControllerCanCustomerOutResult = NonNullable<Awaited<ReturnType<typeof cellControllerCanCustomerOut>>>
export type KeyLogControllerTakeKeyResult = NonNullable<Awaited<ReturnType<typeof keyLogControllerTakeKey>>>
export type KeyLogControllerReturnKeyResult = NonNullable<Awaited<ReturnType<typeof keyLogControllerReturnKey>>>
export type KeyLogControllerFindAllResult = NonNullable<Awaited<ReturnType<typeof keyLogControllerFindAll>>>
export type AppControllerGetHealthResult = NonNullable<Awaited<ReturnType<typeof appControllerGetHealth>>>
