// Mock data for the application

// Key cells data
export const initialKeyCells = [
    {
        id: "cell-1-101",
        floor: 1,
        classroom: "101",
        isLocked: false,
        currentHolder: null,
    },
    {
        id: "cell-1-102",
        floor: 1,
        classroom: "102",
        isAvailable: false,
        isLocked: false,
        currentHolder: "Иванов И.И.",
    },
    {
        id: "cell-1-103",
        floor: 1,
        classroom: "103",
        isAvailable: true,
        isLocked: true,
        currentHolder: null,
    },
    {
        id: "cell-1-104",
        floor: 1,
        classroom: "104",
        isAvailable: true,
        isLocked: false,
        currentHolder: null,
    },
    {
        id: "cell-2-201",
        floor: 2,
        classroom: "201",
        isAvailable: true,
        isLocked: false,
        currentHolder: null,
    },
    {
        id: "cell-2-202",
        floor: 2,
        classroom: "202",
        isAvailable: false,
        isLocked: false,
        currentHolder: "Петров П.П.",
    },
    {
        id: "cell-2-203",
        floor: 2,
        classroom: "203",
        isAvailable: true,
        isLocked: false,
        currentHolder: null,
    },
    {
        id: "cell-3-301",
        floor: 3,
        classroom: "301",
        isAvailable: false,
        isLocked: false,
        currentHolder: "Сидоров С.С.",
    },
    {
        id: "cell-3-302",
        floor: 3,
        classroom: "302",
        isAvailable: true,
        isLocked: false,
        currentHolder: null,
    },
    {
        id: "cell-3-3011",
        floor: 3,
        classroom: "301",
        isAvailable: false,
        isLocked: false,
        currentHolder: "Сидоров С.С.",
    },
    {
        id: "cell-3-3022",
        floor: 3,
        classroom: "302",
        isAvailable: true,
        isLocked: false,
        currentHolder: null,
    },
    {
        id: "cell-3-30112",
        floor: 3,
        classroom: "301",
        isAvailable: false,
        isLocked: false,
        currentHolder: "Сидоров С.С.",
    },
    {
        id: "cell-3-30222",
        floor: 3,
        classroom: "302",
        isAvailable: true,
        isLocked: false,
        currentHolder: null,
    },
    {
        id: "cell-3-3022222",
        floor: 3,
        classroom: "302",
        isAvailable: true,
        isLocked: false,
        currentHolder: null,
    },
    {
        id: "cell-3-302222",
        floor: 3,
        classroom: "302",
        isAvailable: true,
        isLocked: false,
        currentHolder: null,
    },
];

// Logs data
export const initialLogs = [
    {
        id: "log-1",
        cellId: "cell-1-101",
        timestamp: new Date(2025, 4, 10, 9, 0).getTime(),
        userName: "Иванов И.И.",
        action: "take",
        roomNumber: "101",
        floor: 1,
    },
    {
        id: "log-2",
        cellId: "cell-1-101",
        timestamp: new Date(2025, 4, 10, 11, 30).getTime(),
        userName: "Иванов И.И.",
        action: "return",
        roomNumber: "101",
        floor: 1,
    },
    {
        id: "log-3",
        cellId: "cell-1-102",
        timestamp: new Date(2025, 4, 10, 10, 15).getTime(),
        userName: "Иванов И.И.",
        action: "take",
        roomNumber: "102",
        floor: 1,
    },
    {
        id: "log-4",
        cellId: "cell-2-202",
        timestamp: new Date(2025, 4, 10, 9, 45).getTime(),
        userName: "Петров П.П.",
        action: "take",
        roomNumber: "202",
        floor: 2,
    },
    {
        id: "log-5",
        cellId: "cell-3-301",
        timestamp: new Date(2025, 4, 10, 8, 30).getTime(),
        userName: "Сидоров С.С.",
        action: "take",
        roomNumber: "301",
        floor: 3,
    },
    {
        id: "log-6",
        cellId: "cell-1-103",
        timestamp: new Date(2025, 4, 9, 16, 0).getTime(),
        userName: "Администратор",
        action: "lock",
        roomNumber: "103",
        floor: 1,
    },
    {
        id: "log-7",
        cellId: "cell-1-104",
        timestamp: new Date(2025, 4, 9, 15, 45).getTime(),
        userName: "Смирнов А.А.",
        action: "return",
        roomNumber: "104",
        floor: 1,
    },
    {
        id: "log-8",
        cellId: "cell-2-203",
        timestamp: new Date(2025, 4, 9, 14, 30).getTime(),
        userName: "Козлов В.В.",
        action: "return",
        roomNumber: "203",
        floor: 2,
    },
    {
        id: "log-9",
        cellId: "cell-3-302",
        timestamp: new Date(2025, 4, 9, 13, 15).getTime(),
        userName: "Новиков Д.Д.",
        action: "return",
        roomNumber: "302",
        floor: 3,
    },
    {
        id: "log-10",
        cellId: "cell-1-103",
        timestamp: new Date(2025, 4, 8, 17, 0).getTime(),
        userName: "Администратор",
        action: "unlock",
        roomNumber: "103",
        floor: 1,
    },
];

// Users data
export const initialUsers = [
    {
        id: "user-1",
        fullName: "Иванов Иван Иванович",
        cardNumber: "T12345",
        role: "teacher" as const,
    },
    {
        id: "user-2",
        fullName: "Петров Петр Петрович",
        cardNumber: "T23456",
        role: "teacher" as const,
    },
    {
        id: "user-3",
        fullName: "Сидоров Сидор Сидорович",
        cardNumber: "T34567",
        role: "teacher" as const,
    },
    {
        id: "user-4",
        fullName: "Смирнов Алексей Алексеевич",
        cardNumber: "T45678",
        role: "teacher" as const,
    },
    {
        id: "user-5",
        fullName: "Козлов Владимир Владимирович",
        cardNumber: "T56789",
        role: "teacher" as const,
    },
    {
        id: "user-6",
        fullName: "Новиков Дмитрий Дмитриевич",
        cardNumber: "T67890",
        role: "teacher" as const,
    },
    {
        id: "user-7",
        fullName: "Соколов Михаил Михайлович",
        cardNumber: "S12345",
        role: "student" as const,
    },
    {
        id: "user-8",
        fullName: "Попов Андрей Андреевич",
        cardNumber: "S23456",
        role: "student" as const,
    },
];
